### ISSUE TITLE
[Bug] app - file issue menu opens new bug instead of chooser for bug or feature

### ISSUE THREAD

**Issue by masukomi** [dacharyc/prfocus-website#46] opened 2024-07-26 14:48 UTC
what happens: 
When you choose "File an issue" in the app it goes to https://github.com/dacharyc/prfocus-website/issues/new

What should happen

I believe it should go to https://github.com/dacharyc/prfocus-website/issues/new/choose where you are presented with a choice of creating a  feature or bug issue.

**Comment by dacharyc** [comment] 2024-07-27 00:18
Heya - this was an intentional design choice. The "File an issue" option is right above the "Request a feature" option - my intent was to provide you with both options so you could easily get the one you wanted without having to muck about with manually adding a lot of labels or choosing the issue type.

<img width="372" alt="Screenshot 2024-07-26 at 8 12 07 PM" src="https://github.com/user-attachments/assets/5b3245be-061d-47a7-80b8-d2f71e78d101">

 I _hoped_ this would make things more convenient for people. But I guess if you don't notice the other option is there, you may not realize they pre-populate the correct template and labels for the type you choose. (Maybe it would be more explicit if I said "File a bug report" instead of "File an issue?")

I'm going to go ahead and close this because it's working as designed. But if other folks leave similar feedback in the future, I'll revisit changing this behavior.

**Closed by dacharyc** 2024-07-27 00:18 UTC
Labels: bug, PR Focus App
